2020-08-13 20:44:52,559 : INFO : Start of Prediction
2020-08-13 20:44:52,559 : INFO : run_id:2020-08-13_204452_539692384
2020-08-13 20:44:52,559 : INFO : Start of Data Load, validation and transformation
2020-08-13 20:44:52,560 : INFO : Start of Archiving Old Rejected Files...
2020-08-13 20:44:52,560 : INFO : End of Archiving Old Rejected Files...
2020-08-13 20:44:52,560 : INFO : Start of Archiving Old Validated Files...
2020-08-13 20:44:52,560 : INFO : End of Archiving Old Validated Files...
2020-08-13 20:44:52,560 : INFO : Start of Archiving Old Processed Files...
2020-08-13 20:44:52,561 : INFO : End of Archiving Old Processed Files...
2020-08-13 20:44:52,561 : INFO : Start of Archiving Old Result Files...
2020-08-13 20:44:52,562 : INFO : End of Archiving Old Result Files...
2020-08-13 20:44:52,562 : INFO : Start of Reading values From Schema...
2020-08-13 20:44:52,563 : INFO : End of Reading values From Schema...
2020-08-13 20:44:52,563 : INFO : Start of Validating Column Length...
2020-08-13 20:44:52,564 : INFO : End of Validating Column Length...
2020-08-13 20:44:52,564 : INFO : Start of Validating Missing Values...
2020-08-13 20:44:52,564 : INFO : End of Validating Missing Values...
2020-08-13 20:44:52,564 : INFO : Start of Replacing Missing Values with NULL...
2020-08-13 20:44:52,564 : INFO : End of Replacing Missing Values with NULL...
2020-08-13 20:44:52,564 : INFO : Start of Creating Table...
2020-08-13 20:44:52,565 : INFO : Opened prediction database successfully
2020-08-13 20:44:52,812 : INFO : CREATE TABLE prediction_raw_data_t column_name
2020-08-13 20:44:52,996 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:53,134 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:53,317 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:53,432 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:53,826 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:54,007 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:54,123 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:54,249 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:54,366 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:54,483 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:54,610 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:54,714 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:54,831 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:54,948 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2020-08-13 20:44:54,949 : INFO : End of Creating Table...
2020-08-13 20:44:54,954 : INFO : Opened prediction database successfully
2020-08-13 20:44:54,954 : INFO : Start of Inserting Data into Table...
2020-08-13 20:44:54,955 : INFO : End of Inserting Data into Table...
2020-08-13 20:44:54,955 : INFO : Start of Exporting Data into CSV...
2020-08-13 20:44:54,957 : INFO : Opened prediction database successfully
2020-08-13 20:44:54,960 : INFO : End of Exporting Data into CSV...
2020-08-13 20:44:54,962 : INFO : Start of Moving Processed Files...
2020-08-13 20:44:54,964 : INFO : End of Moving Processed Files...
2020-08-13 20:44:54,964 : INFO : End of Data Load, validation and transformation
2020-08-13 20:44:54,964 : INFO : Start of Preprocessing...
2020-08-13 20:44:54,965 : INFO : Start of reading dataset...
2020-08-13 20:44:55,007 : INFO : End of reading dataset...
2020-08-13 20:44:55,008 : INFO : Start of Droping Columns...
2020-08-13 20:44:55,011 : INFO : End of Droping Columns...
2020-08-13 20:44:55,013 : INFO : Start of replacing invalid values...
2020-08-13 20:44:55,059 : INFO : end of replacing invalid values...
2020-08-13 20:44:55,060 : INFO : Start of encode Categorical Values ...
2020-08-13 20:44:55,069 : ERROR : Exception raised while splitting features and label:'Column not found: Approved'
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 201, in encode_categorical_values
    EducationLevel_encoding = data.groupby(['EducationLevel'])['Approved'].mean().to_dict()
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\base.py", line 268, in __getitem__
    raise KeyError("Column not found: {key}".format(key=key))
KeyError: 'Column not found: Approved'
2020-08-13 20:44:55,099 : ERROR : Unsuccessful End of Preprocessing...
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 201, in encode_categorical_values
    EducationLevel_encoding = data.groupby(['EducationLevel'])['Approved'].mean().to_dict()
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\base.py", line 268, in __getitem__
    raise KeyError("Column not found: {key}".format(key=key))
KeyError: 'Column not found: Approved'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 365, in preprocess_predictset
    data = self.encode_categorical_values(data)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 217, in encode_categorical_values
    raise Exception()
Exception
2020-08-13 20:44:55,101 : ERROR : Unsuccessful End of Prediction
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 201, in encode_categorical_values
    EducationLevel_encoding = data.groupby(['EducationLevel'])['Approved'].mean().to_dict()
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\core\base.py", line 268, in __getitem__
    raise KeyError("Column not found: {key}".format(key=key))
KeyError: 'Column not found: Approved'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 365, in preprocess_predictset
    data = self.encode_categorical_values(data)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 217, in encode_categorical_values
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\prediction\predict_model.py", line 48, in batch_predict_from_model
    self.X = self.preProcess.preprocess_predictset()
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 382, in preprocess_predictset
    raise Exception
Exception
