2020-08-13 09:33:25,229 : INFO : Start of Training
2020-08-13 09:33:25,229 : INFO : Run_id:2020-08-13_093325_208431895
2020-08-13 09:33:25,229 : INFO : Start of Data Load, validation and transformation
2020-08-13 09:33:25,229 : INFO : Start of Archiving Old Rejected Files...
2020-08-13 09:33:25,229 : INFO : End of Archiving Old Rejected Files...
2020-08-13 09:33:25,230 : INFO : Start of Archiving Old Validated Files...
2020-08-13 09:33:25,230 : INFO : End of Archiving Old Validated Files...
2020-08-13 09:33:25,230 : INFO : Start of Archiving Old Processed Files...
2020-08-13 09:33:25,232 : INFO : End of Archiving Old Processed Files...
2020-08-13 09:33:25,232 : INFO : Start of Archiving Old Result Files...
2020-08-13 09:33:25,233 : INFO : End of Archiving Old Result Files...
2020-08-13 09:33:25,233 : INFO : Start of Reading values From Schema...
2020-08-13 09:33:25,233 : INFO : End of Reading values From Schema...
2020-08-13 09:33:25,233 : INFO : Start of Validating Column Length...
2020-08-13 09:33:25,241 : INFO : End of Validating Column Length...
2020-08-13 09:33:25,241 : INFO : Start of Validating Missing Values...
2020-08-13 09:33:25,252 : INFO : End of Validating Missing Values...
2020-08-13 09:33:25,252 : INFO : Start of Replacing Missing Values with NULL...
2020-08-13 09:33:25,272 : INFO : Credit_Approval_rename_data.csv: File Transformed successfully!!
2020-08-13 09:33:25,272 : INFO : End of Replacing Missing Values with NULL...
2020-08-13 09:33:25,272 : INFO : Start of Creating Table...
2020-08-13 09:33:25,273 : INFO : Opened training database successfully
2020-08-13 09:33:25,475 : INFO : CREATE TABLE training_raw_data_t column_name
2020-08-13 09:33:25,603 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:25,762 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:25,922 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:26,073 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:26,241 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:26,365 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:26,507 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:26,674 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:26,808 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:26,903 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:27,030 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:27,135 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:27,252 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:27,357 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:27,465 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-13 09:33:27,467 : INFO : End of Creating Table...
2020-08-13 09:33:27,471 : INFO : Opened training database successfully
2020-08-13 09:33:27,472 : INFO : Start of Inserting Data into Table...
2020-08-13 09:34:55,417 : INFO : End of Inserting Data into Table...
2020-08-13 09:34:55,418 : INFO : Start of Exporting Data into CSV...
2020-08-13 09:34:55,424 : INFO : Opened training database successfully
2020-08-13 09:34:55,474 : INFO : End of Exporting Data into CSV...
2020-08-13 09:34:55,476 : INFO : Start of Moving Processed Files...
2020-08-13 09:34:55,480 : INFO : Moved the already processed file Credit_Approval_rename_data.csv
2020-08-13 09:34:55,480 : INFO : End of Moving Processed Files...
2020-08-13 09:34:55,481 : INFO : End of Data Load, validation and transformation
2020-08-13 09:34:55,481 : INFO : Start of Preprocessing...
2020-08-13 09:34:55,481 : INFO : Start of reading dataset...
2020-08-13 09:34:55,495 : INFO : End of reading dataset...
2020-08-13 09:34:55,496 : INFO : Start of Droping Columns...
2020-08-13 09:34:55,497 : INFO : End of Droping Columns...
2020-08-13 09:34:55,498 : INFO : Start of replacing invalid values...
2020-08-13 09:34:55,542 : INFO : end of replacing invalid values...
2020-08-13 09:34:55,542 : INFO : Start of encode Categorical Values ...
2020-08-13 09:34:55,727 : INFO : end of encode Categorical Values...
2020-08-13 09:34:55,727 : INFO : Start of feature encoding...
2020-08-13 09:34:55,793 : INFO : End of feature encoding...
2020-08-13 09:34:55,813 : INFO : Start of Droping Columns...
2020-08-13 09:34:55,814 : INFO : End of Droping Columns...
2020-08-13 09:34:55,815 : INFO : Start of finding missing values...
2020-08-13 09:34:55,822 : INFO : End of finding missing values...
2020-08-13 09:34:55,822 : INFO : Start of imputing missing values...
2020-08-13 09:34:55,921 : INFO : End of imputing missing values...
2020-08-13 09:34:55,922 : INFO : Start of saving dataset...
2020-08-13 09:34:55,982 : INFO : End of saving dataset...
2020-08-13 09:34:55,982 : INFO : Start feature selection of dataset...
2020-08-13 09:34:55,983 : ERROR : Exception raised while feature selection of dataset: %s[Errno 2] File b'data/training_data_encode/encode.csv' does not exist: b'data/training_data_encode/encode.csv'
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 233, in Feature_Selection
    data = pd.read_csv(self.data_path + '_encode/encode.csv')
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'data/training_data_encode/encode.csv' does not exist: b'data/training_data_encode/encode.csv'
2020-08-13 09:34:56,001 : ERROR : Unsuccessful End of Preprocessing...
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 233, in Feature_Selection
    data = pd.read_csv(self.data_path + '_encode/encode.csv')
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'data/training_data_encode/encode.csv' does not exist: b'data/training_data_encode/encode.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 340, in preprocess_trainset
    data = self.Feature_Selection()
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 255, in Feature_Selection
    raise Exception()
Exception
2020-08-13 09:34:56,004 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 233, in Feature_Selection
    data = pd.read_csv(self.data_path + '_encode/encode.csv')
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'data/training_data_encode/encode.csv' does not exist: b'data/training_data_encode/encode.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 340, in preprocess_trainset
    data = self.Feature_Selection()
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 255, in Feature_Selection
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\training\train_model.py", line 54, in training_model
    self.X, self.y = self.preProcess.preprocess_trainset()
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 347, in preprocess_trainset
    raise Exception
Exception
