2020-08-12 09:28:13,788 : INFO : Start of Training
2020-08-12 09:28:13,788 : INFO : Run_id:2020-08-12_092813_938013438
2020-08-12 09:28:13,788 : INFO : Start of Data Load, validation and transformation
2020-08-12 09:28:13,789 : INFO : Start of Archiving Old Rejected Files...
2020-08-12 09:28:13,789 : INFO : End of Archiving Old Rejected Files...
2020-08-12 09:28:13,789 : INFO : Start of Archiving Old Validated Files...
2020-08-12 09:28:13,817 : INFO : End of Archiving Old Validated Files...
2020-08-12 09:28:13,817 : INFO : Start of Archiving Old Processed Files...
2020-08-12 09:28:13,817 : INFO : End of Archiving Old Processed Files...
2020-08-12 09:28:13,818 : INFO : Start of Archiving Old Result Files...
2020-08-12 09:28:13,818 : INFO : End of Archiving Old Result Files...
2020-08-12 09:28:13,819 : INFO : Start of Reading values From Schema...
2020-08-12 09:28:13,819 : INFO : End of Reading values From Schema...
2020-08-12 09:28:13,819 : INFO : Start of Validating Column Length...
2020-08-12 09:28:13,819 : INFO : End of Validating Column Length...
2020-08-12 09:28:13,819 : INFO : Start of Validating Missing Values...
2020-08-12 09:28:13,820 : INFO : End of Validating Missing Values...
2020-08-12 09:28:13,820 : INFO : Start of Replacing Missing Values with NULL...
2020-08-12 09:28:13,820 : INFO : End of Replacing Missing Values with NULL...
2020-08-12 09:28:13,820 : INFO : Start of Creating Table...
2020-08-12 09:28:13,820 : INFO : Opened training database successfully
2020-08-12 09:28:13,821 : INFO : Tables created successfully
2020-08-12 09:28:13,821 : INFO : Closed training database successfully
2020-08-12 09:28:13,821 : INFO : End of Creating Table...
2020-08-12 09:28:13,821 : INFO : Opened training database successfully
2020-08-12 09:28:13,822 : INFO : Start of Inserting Data into Table...
2020-08-12 09:28:13,822 : INFO : End of Inserting Data into Table...
2020-08-12 09:28:13,822 : INFO : Start of Exporting Data into CSV...
2020-08-12 09:28:13,822 : INFO : Opened training database successfully
2020-08-12 09:28:13,855 : INFO : End of Exporting Data into CSV...
2020-08-12 09:28:13,856 : INFO : Start of Moving Processed Files...
2020-08-12 09:28:13,856 : INFO : End of Moving Processed Files...
2020-08-12 09:28:13,857 : INFO : End of Data Load, validation and transformation
2020-08-12 09:28:13,857 : INFO : Start of Preprocessing...
2020-08-12 09:28:13,857 : INFO : Start of reading dataset...
2020-08-12 09:28:13,866 : INFO : End of reading dataset...
2020-08-12 09:28:13,866 : INFO : Start of Droping Columns...
2020-08-12 09:28:13,868 : INFO : End of Droping Columns...
2020-08-12 09:28:13,868 : INFO : Start of replacing invalid values...
2020-08-12 09:28:13,907 : INFO : end of replacing invalid values...
2020-08-12 09:28:13,908 : INFO : Start of encode Categorical Values ...
2020-08-12 09:28:13,922 : INFO : end of encode Categorical Values...
2020-08-12 09:28:13,922 : INFO : Start of feature encoding...
2020-08-12 09:28:13,940 : INFO : End of feature encoding...
2020-08-12 09:28:13,942 : INFO : Start of Droping Columns...
2020-08-12 09:28:13,943 : INFO : End of Droping Columns...
2020-08-12 09:28:13,943 : INFO : Start of finding missing values...
2020-08-12 09:28:13,950 : INFO : End of finding missing values...
2020-08-12 09:28:13,950 : INFO : Start of imputing missing values...
2020-08-12 09:28:13,957 : INFO : End of imputing missing values...
2020-08-12 09:28:13,957 : INFO : Start of splitting features and label ...
2020-08-12 09:28:13,958 : INFO : End of splitting features and label ...
2020-08-12 09:28:13,958 : INFO : End of Preprocessing...
2020-08-12 09:28:13,959 : INFO : Start of elbow plotting...
2020-08-12 09:28:14,502 : INFO : The optimum number of clusters is: 3
2020-08-12 09:28:14,502 : INFO : End of elbow plotting...
2020-08-12 09:28:14,502 : INFO : Start of Create clusters...
2020-08-12 09:28:14,534 : INFO : Start of Save Models
2020-08-12 09:28:14,534 : INFO : Start of Save Models
2020-08-12 09:28:14,537 : INFO : Model File KMeans saved
2020-08-12 09:28:14,537 : INFO : Model File KMeans saved
2020-08-12 09:28:14,538 : INFO : End of Save Models
2020-08-12 09:28:14,538 : INFO : End of Save Models
2020-08-12 09:28:14,538 : INFO : succesfully created 3clusters.
2020-08-12 09:28:14,539 : INFO : End of Create clusters...
2020-08-12 09:28:14,544 : INFO : Start of finding best model...
2020-08-12 09:28:14,544 : INFO : Start of finding best params for KNN algo...
2020-08-12 09:28:27,994 : INFO : Knn Forest best params: {'algorithm': 'ball_tree', 'leaf_size': 10, 'n_neighbors': 3, 'p': 1}
2020-08-12 09:28:27,994 : INFO : End of finding best params for knn algo...
2020-08-12 09:28:28,140 : INFO : AUC for knn:0.715646404109589
2020-08-12 09:28:28,141 : INFO : Start of finding best params for randomforest algo...
2020-08-12 09:28:49,461 : INFO : Random Forest best params: {'criterion': 'gini', 'max_depth': 2, 'max_features': 'log2', 'n_estimators': 100}
2020-08-12 09:28:49,461 : INFO : End of finding best params for randomforest algo...
2020-08-12 09:28:49,474 : INFO : AUC for Random Forest:0.8592679794520548
2020-08-12 09:28:49,474 : INFO : End of finding best model...
2020-08-12 09:28:49,474 : INFO : Start of Save Models
2020-08-12 09:28:49,474 : INFO : Start of Save Models
2020-08-12 09:28:49,478 : INFO : Model File RandomForest0 saved
2020-08-12 09:28:49,478 : INFO : Model File RandomForest0 saved
2020-08-12 09:28:49,478 : INFO : End of Save Models
2020-08-12 09:28:49,478 : INFO : End of Save Models
2020-08-12 09:28:49,482 : INFO : Start of finding best model...
2020-08-12 09:28:49,482 : INFO : Start of finding best params for KNN algo...
2020-08-12 09:28:49,831 : ERROR : Exception raised while finding best params for knn algo:Expected n_neighbors <= n_samples,  but n_samples = 2, n_neighbors = 3
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 105, in get_best_params_for_KNN
    self.grid.fit(train_x, train_y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 710, in fit
    self._run_search(evaluate_candidates)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 1151, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 689, in evaluate_candidates
    cv.split(X, y, groups)))
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 1032, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_validation.py", line 544, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_validation.py", line 591, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\metrics\_scorer.py", line 89, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\metrics\_scorer.py", line 371, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py", line 369, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\neighbors\_classification.py", line 173, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\neighbors\_base.py", line 617, in kneighbors
    (n_samples_fit, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 2, n_neighbors = 3
2020-08-12 09:28:49,832 : ERROR : Exception raised while finding best model:
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 105, in get_best_params_for_KNN
    self.grid.fit(train_x, train_y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 710, in fit
    self._run_search(evaluate_candidates)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 1151, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 689, in evaluate_candidates
    cv.split(X, y, groups)))
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 1032, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_validation.py", line 544, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_validation.py", line 591, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\metrics\_scorer.py", line 89, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\metrics\_scorer.py", line 371, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py", line 369, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\neighbors\_classification.py", line 173, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\neighbors\_base.py", line 617, in kneighbors
    (n_samples_fit, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 2, n_neighbors = 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 182, in get_best_model
    self.knn = self.get_best_params_for_KNN(train_x, train_y)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 124, in get_best_params_for_KNN
    raise Exception()
Exception
2020-08-12 09:28:49,833 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 105, in get_best_params_for_KNN
    self.grid.fit(train_x, train_y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 710, in fit
    self._run_search(evaluate_candidates)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 1151, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 689, in evaluate_candidates
    cv.split(X, y, groups)))
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 1032, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_validation.py", line 544, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_validation.py", line 591, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\metrics\_scorer.py", line 89, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\metrics\_scorer.py", line 371, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py", line 369, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\neighbors\_classification.py", line 173, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\neighbors\_base.py", line 617, in kneighbors
    (n_samples_fit, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 2, n_neighbors = 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 182, in get_best_model
    self.knn = self.get_best_params_for_KNN(train_x, train_y)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 124, in get_best_params_for_KNN
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\training\train_model.py", line 78, in training_model
    best_model_name, best_model = self.modelTuner.get_best_model(x_train, y_train, x_test, y_test)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 215, in get_best_model
    raise Exception()
Exception
