2020-08-12 10:32:04,604 : INFO : Start of Training
2020-08-12 10:32:04,604 : INFO : Run_id:2020-08-12_103204_433776542
2020-08-12 10:32:04,605 : INFO : Start of Data Load, validation and transformation
2020-08-12 10:32:04,605 : INFO : Start of Archiving Old Rejected Files...
2020-08-12 10:32:04,605 : INFO : End of Archiving Old Rejected Files...
2020-08-12 10:32:04,605 : INFO : Start of Archiving Old Validated Files...
2020-08-12 10:32:04,609 : INFO : End of Archiving Old Validated Files...
2020-08-12 10:32:04,609 : INFO : Start of Archiving Old Processed Files...
2020-08-12 10:32:04,611 : INFO : End of Archiving Old Processed Files...
2020-08-12 10:32:04,611 : INFO : Start of Archiving Old Result Files...
2020-08-12 10:32:04,612 : INFO : End of Archiving Old Result Files...
2020-08-12 10:32:04,612 : INFO : Start of Reading values From Schema...
2020-08-12 10:32:04,613 : INFO : End of Reading values From Schema...
2020-08-12 10:32:04,613 : INFO : Start of Validating Column Length...
2020-08-12 10:32:04,621 : INFO : End of Validating Column Length...
2020-08-12 10:32:04,623 : INFO : Start of Validating Missing Values...
2020-08-12 10:32:04,633 : INFO : End of Validating Missing Values...
2020-08-12 10:32:04,633 : INFO : Start of Replacing Missing Values with NULL...
2020-08-12 10:32:04,653 : INFO : Credit_Approval_rename_data.csv: File Transformed successfully!!
2020-08-12 10:32:04,653 : INFO : End of Replacing Missing Values with NULL...
2020-08-12 10:32:04,653 : INFO : Start of Creating Table...
2020-08-12 10:32:04,654 : INFO : Opened training database successfully
2020-08-12 10:32:04,837 : INFO : CREATE TABLE training_raw_data_t column_name
2020-08-12 10:32:04,948 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:05,080 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:05,167 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:05,255 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:05,354 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:05,463 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:05,575 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:05,684 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:05,804 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:05,904 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:06,065 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:06,212 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:06,388 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:06,578 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:06,751 : INFO : ALTER TABLE training_raw_data_t ADD COLUMN
2020-08-12 10:32:06,751 : INFO : End of Creating Table...
2020-08-12 10:32:06,753 : INFO : Opened training database successfully
2020-08-12 10:32:06,753 : INFO : Start of Inserting Data into Table...
2020-08-12 10:33:37,828 : INFO : End of Inserting Data into Table...
2020-08-12 10:33:37,829 : INFO : Start of Exporting Data into CSV...
2020-08-12 10:33:37,835 : INFO : Opened training database successfully
2020-08-12 10:33:37,878 : INFO : End of Exporting Data into CSV...
2020-08-12 10:33:37,880 : INFO : Start of Moving Processed Files...
2020-08-12 10:33:37,888 : INFO : Moved the already processed file Credit_Approval_rename_data.csv
2020-08-12 10:33:37,889 : INFO : End of Moving Processed Files...
2020-08-12 10:33:37,889 : INFO : End of Data Load, validation and transformation
2020-08-12 10:33:37,889 : INFO : Start of Preprocessing...
2020-08-12 10:33:37,890 : INFO : Start of reading dataset...
2020-08-12 10:33:37,925 : INFO : End of reading dataset...
2020-08-12 10:33:37,925 : INFO : Start of Droping Columns...
2020-08-12 10:33:37,933 : INFO : End of Droping Columns...
2020-08-12 10:33:37,933 : INFO : Start of replacing invalid values...
2020-08-12 10:33:38,127 : INFO : end of replacing invalid values...
2020-08-12 10:33:38,127 : INFO : Start of encode Categorical Values ...
2020-08-12 10:33:38,190 : INFO : end of encode Categorical Values...
2020-08-12 10:33:38,191 : INFO : Start of feature encoding...
2020-08-12 10:33:38,239 : INFO : End of feature encoding...
2020-08-12 10:33:38,242 : INFO : Start of Droping Columns...
2020-08-12 10:33:38,244 : INFO : End of Droping Columns...
2020-08-12 10:33:38,244 : INFO : Start of finding missing values...
2020-08-12 10:33:38,253 : INFO : End of finding missing values...
2020-08-12 10:33:38,253 : INFO : Start of imputing missing values...
2020-08-12 10:33:38,263 : INFO : End of imputing missing values...
2020-08-12 10:33:38,263 : INFO : Start of splitting features and label ...
2020-08-12 10:33:38,265 : INFO : End of splitting features and label ...
2020-08-12 10:33:38,265 : INFO : End of Preprocessing...
2020-08-12 10:33:38,266 : INFO : Start of elbow plotting...
2020-08-12 10:33:39,403 : INFO : The optimum number of clusters is: 3
2020-08-12 10:33:39,403 : INFO : End of elbow plotting...
2020-08-12 10:33:39,403 : INFO : Start of Create clusters...
2020-08-12 10:33:39,435 : INFO : Start of Save Models
2020-08-12 10:33:39,435 : INFO : Start of Save Models
2020-08-12 10:33:39,436 : INFO : Model File KMeans saved
2020-08-12 10:33:39,436 : INFO : Model File KMeans saved
2020-08-12 10:33:39,436 : INFO : End of Save Models
2020-08-12 10:33:39,436 : INFO : End of Save Models
2020-08-12 10:33:39,437 : INFO : succesfully created 3clusters.
2020-08-12 10:33:39,437 : INFO : End of Create clusters...
2020-08-12 10:33:39,441 : INFO : Start of finding best model...
2020-08-12 10:33:39,442 : INFO : Start of finding best params for KNN algo...
2020-08-12 10:33:48,416 : INFO : Knn Forest best params: {'algorithm': 'ball_tree', 'leaf_size': 10, 'n_neighbors': 3, 'p': 1}
2020-08-12 10:33:48,416 : INFO : End of finding best params for knn algo...
2020-08-12 10:33:48,592 : INFO : AUC for knn:0.715646404109589
2020-08-12 10:33:48,592 : INFO : Start of finding best params for randomforest algo...
2020-08-12 10:33:50,207 : INFO : Random Forest best params: {'criterion': 'gini', 'max_depth': 3, 'max_features': 'log2', 'n_estimators': 3}
2020-08-12 10:33:50,207 : INFO : End of finding best params for randomforest algo...
2020-08-12 10:33:50,210 : INFO : AUC for Random Forest:0.8377568493150684
2020-08-12 10:33:50,210 : INFO : End of finding best model...
2020-08-12 10:33:50,210 : INFO : Start of Save Models
2020-08-12 10:33:50,210 : INFO : Start of Save Models
2020-08-12 10:33:50,211 : INFO : Model File RandomForest0 saved
2020-08-12 10:33:50,211 : INFO : Model File RandomForest0 saved
2020-08-12 10:33:50,211 : INFO : End of Save Models
2020-08-12 10:33:50,211 : INFO : End of Save Models
2020-08-12 10:33:50,215 : INFO : Start of finding best model...
2020-08-12 10:33:50,215 : INFO : Start of finding best params for KNN algo...
2020-08-12 10:33:54,825 : ERROR : Exception raised while finding best params for knn algo:Expected n_neighbors <= n_samples,  but n_samples = 2, n_neighbors = 3
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 111, in get_best_params_for_KNN
    self.grid.fit(train_x, train_y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 710, in fit
    self._run_search(evaluate_candidates)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 1151, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 689, in evaluate_candidates
    cv.split(X, y, groups)))
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 1032, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_validation.py", line 544, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_validation.py", line 591, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\metrics\_scorer.py", line 89, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\metrics\_scorer.py", line 371, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py", line 369, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\neighbors\_classification.py", line 173, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\neighbors\_base.py", line 617, in kneighbors
    (n_samples_fit, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 2, n_neighbors = 3
2020-08-12 10:33:54,830 : ERROR : Exception raised while finding best model:
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 111, in get_best_params_for_KNN
    self.grid.fit(train_x, train_y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 710, in fit
    self._run_search(evaluate_candidates)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 1151, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 689, in evaluate_candidates
    cv.split(X, y, groups)))
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 1032, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_validation.py", line 544, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_validation.py", line 591, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\metrics\_scorer.py", line 89, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\metrics\_scorer.py", line 371, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py", line 369, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\neighbors\_classification.py", line 173, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\neighbors\_base.py", line 617, in kneighbors
    (n_samples_fit, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 2, n_neighbors = 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 188, in get_best_model
    self.knn = self.get_best_params_for_KNN(train_x, train_y)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 130, in get_best_params_for_KNN
    raise Exception()
Exception
2020-08-12 10:33:54,831 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 111, in get_best_params_for_KNN
    self.grid.fit(train_x, train_y)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 710, in fit
    self._run_search(evaluate_candidates)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 1151, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_search.py", line 689, in evaluate_candidates
    cv.split(X, y, groups)))
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 1032, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\joblib\parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_validation.py", line 544, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\model_selection\_validation.py", line 591, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\metrics\_scorer.py", line 89, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\metrics\_scorer.py", line 371, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py", line 369, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\neighbors\_classification.py", line 173, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "C:\Users\sreeh\AppData\Roaming\Python\Python36\site-packages\sklearn\neighbors\_base.py", line 617, in kneighbors
    (n_samples_fit, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 2, n_neighbors = 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 188, in get_best_model
    self.knn = self.get_best_params_for_KNN(train_x, train_y)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 130, in get_best_params_for_KNN
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\training\train_model.py", line 78, in training_model
    best_model_name, best_model = self.modelTuner.get_best_model(x_train, y_train, x_test, y_test)
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\tuning\model_tuner.py", line 221, in get_best_model
    raise Exception()
Exception
