2020-08-13 10:20:02,288 : INFO : Start of Training
2020-08-13 10:20:02,288 : INFO : Run_id:2020-08-13_102002_507489489
2020-08-13 10:20:02,288 : INFO : Start of Data Load, validation and transformation
2020-08-13 10:20:02,289 : INFO : Start of Archiving Old Rejected Files...
2020-08-13 10:20:02,289 : INFO : End of Archiving Old Rejected Files...
2020-08-13 10:20:02,289 : INFO : Start of Archiving Old Validated Files...
2020-08-13 10:20:02,293 : INFO : End of Archiving Old Validated Files...
2020-08-13 10:20:02,293 : INFO : Start of Archiving Old Processed Files...
2020-08-13 10:20:02,296 : INFO : End of Archiving Old Processed Files...
2020-08-13 10:20:02,296 : INFO : Start of Archiving Old Result Files...
2020-08-13 10:20:02,297 : INFO : End of Archiving Old Result Files...
2020-08-13 10:20:02,297 : INFO : Start of Reading values From Schema...
2020-08-13 10:20:02,297 : INFO : End of Reading values From Schema...
2020-08-13 10:20:02,298 : INFO : Start of Validating Column Length...
2020-08-13 10:20:02,298 : INFO : End of Validating Column Length...
2020-08-13 10:20:02,298 : INFO : Start of Validating Missing Values...
2020-08-13 10:20:02,298 : INFO : End of Validating Missing Values...
2020-08-13 10:20:02,298 : INFO : Start of Replacing Missing Values with NULL...
2020-08-13 10:20:02,299 : INFO : End of Replacing Missing Values with NULL...
2020-08-13 10:20:02,299 : INFO : Start of Creating Table...
2020-08-13 10:20:02,301 : INFO : Opened training database successfully
2020-08-13 10:20:02,302 : INFO : Tables created successfully
2020-08-13 10:20:02,302 : INFO : Closed training database successfully
2020-08-13 10:20:02,302 : INFO : End of Creating Table...
2020-08-13 10:20:02,303 : INFO : Opened training database successfully
2020-08-13 10:20:02,303 : INFO : Start of Inserting Data into Table...
2020-08-13 10:20:02,303 : INFO : End of Inserting Data into Table...
2020-08-13 10:20:02,303 : INFO : Start of Exporting Data into CSV...
2020-08-13 10:20:02,304 : INFO : Opened training database successfully
2020-08-13 10:20:02,319 : INFO : End of Exporting Data into CSV...
2020-08-13 10:20:02,319 : INFO : Start of Moving Processed Files...
2020-08-13 10:20:02,320 : INFO : End of Moving Processed Files...
2020-08-13 10:20:02,320 : INFO : End of Data Load, validation and transformation
2020-08-13 10:20:02,320 : INFO : Start of Preprocessing...
2020-08-13 10:20:02,320 : INFO : Start of reading dataset...
2020-08-13 10:20:02,329 : INFO : End of reading dataset...
2020-08-13 10:20:02,329 : INFO : Start of Droping Columns...
2020-08-13 10:20:02,330 : INFO : End of Droping Columns...
2020-08-13 10:20:02,331 : INFO : Start of replacing invalid values...
2020-08-13 10:20:02,376 : INFO : end of replacing invalid values...
2020-08-13 10:20:02,376 : INFO : Start of encode Categorical Values ...
2020-08-13 10:20:02,388 : INFO : end of encode Categorical Values...
2020-08-13 10:20:02,388 : INFO : Start of feature encoding...
2020-08-13 10:20:02,411 : INFO : End of feature encoding...
2020-08-13 10:20:02,415 : INFO : Start of Droping Columns...
2020-08-13 10:20:02,416 : INFO : End of Droping Columns...
2020-08-13 10:20:02,416 : INFO : Start of finding missing values...
2020-08-13 10:20:02,441 : INFO : End of finding missing values...
2020-08-13 10:20:02,442 : INFO : Start of imputing missing values...
2020-08-13 10:20:02,449 : INFO : End of imputing missing values...
2020-08-13 10:20:02,450 : INFO : Start of saving dataset...
2020-08-13 10:20:02,465 : INFO : End of saving dataset...
2020-08-13 10:20:02,465 : INFO : Start feature selection of dataset...
2020-08-13 10:20:02,465 : ERROR : Exception raised while feature selection of dataset: %s[Errno 2] File b'data/training_data_encode/encode.csv' does not exist: b'data/training_data_encode/encode.csv'
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 233, in Feature_Selection
    data = pd.read_csv(self.data_path + '_encode/encode.csv')
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'data/training_data_encode/encode.csv' does not exist: b'data/training_data_encode/encode.csv'
2020-08-13 10:20:02,466 : ERROR : Unsuccessful End of Preprocessing...
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 233, in Feature_Selection
    data = pd.read_csv(self.data_path + '_encode/encode.csv')
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'data/training_data_encode/encode.csv' does not exist: b'data/training_data_encode/encode.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 340, in preprocess_trainset
    data = self.Feature_Selection()
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 255, in Feature_Selection
    raise Exception()
Exception
2020-08-13 10:20:02,467 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 233, in Feature_Selection
    data = pd.read_csv(self.data_path + '_encode/encode.csv')
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\sreeh\anaconda3\envs\Credit_Approval\lib\site-packages\pandas\io\parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'data/training_data_encode/encode.csv' does not exist: b'data/training_data_encode/encode.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 340, in preprocess_trainset
    data = self.Feature_Selection()
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 255, in Feature_Selection
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\training\train_model.py", line 54, in training_model
    self.X, self.y = self.preProcess.preprocess_trainset()
  File "C:\Users\sreeh\Desktop\group project\actual project\apps\preprocess\preprocessor.py", line 347, in preprocess_trainset
    raise Exception
Exception
